# Generated by Django 5.1.6 on 2025-05-15 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_equipment_newsarticle_plantinglocation_tree_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PlantingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("subscribed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TreeCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("care_type", models.CharField(max_length=100)),
                ("care_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("planted_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.RemoveField(
            model_name="userplanting",
            name="location",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userplanting",
            name="tree",
        ),
        migrations.RemoveField(
            model_name="userplanting",
            name="user",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="notification_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="is_recommended",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="price",
        ),
        migrations.AddField(
            model_name="equipment",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_images/"
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tree_images/"),
        ),
        migrations.AddField(
            model_name="tree",
            name="species",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tree",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tree",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="equipmentorder",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.equipment"
            ),
        ),
        migrations.AddField(
            model_name="equipmentorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plantingplan",
            name="tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.tree"
            ),
        ),
        migrations.AddField(
            model_name="plantingplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usertree",
            name="tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.tree"
            ),
        ),
        migrations.AddField(
            model_name="usertree",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="treecare",
            name="user_tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.usertree"
            ),
        ),
        migrations.DeleteModel(
            name="PlantingLocation",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="UserPlanting",
        ),
    ]
