# Generated by Django 5.1.6 on 2025-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_tree_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="equipment/"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
