# Generated by Django 5.1.6 on 2025-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_purchase_userplanting"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="type",
            field=models.CharField(
                choices=[("tree", "Tree"), ("equipment", "Equipment")],
                default="tree",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verifying", "Verifying"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
