# Generated by Django 5.1.6 on 2025-05-30 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_purchase_type_alter_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplanting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
