# Generated by Django 5.1.6 on 2025-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_userplanting_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplanting",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
