# Generated by Django 5.1.6 on 2025-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_userplanting_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplanting",
            name="slip_url",
            field=models.FileField(blank=True, null=True, upload_to="slips/"),
        ),
    ]
