# Generated by Django 5.1.6 on 2025-05-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_userplanting_slip_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userplanting",
            name="location",
        ),
        migrations.AddField(
            model_name="userplanting",
            name="location_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
