# Generated by Django 5.1.6 on 2025-05-31 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_userplanting_location_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="type",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.equipment"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verifying", "Verifying"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
