# Generated by Django 5.1.6 on 2025-05-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_remove_purchase_image_url_remove_purchase_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="product_name",
        ),
        migrations.AddField(
            model_name="purchase",
            name="product_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="product_name_text",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
        migrations.AddField(
            model_name="userplanting",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
