# Generated by Django 5.1.6 on 2025-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_userequipment_delete_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="userequipment",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userequipment",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
