# Generated by Django 5.1.6 on 2025-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_userequipment_image_url_userequipment_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userequipment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="equipment/"),
        ),
        migrations.AlterField(
            model_name="userequipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอตรวจสอบ"),
                    ("verifying", "กำลังตรวจสอบ"),
                    ("confirmed", "ยืนยันแล้ว"),
                    ("shipping", "กำลังจัดส่ง"),
                    ("delivered", "จัดส่งสำเร็จ"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
