# Generated by Django 5.1.6 on 2025-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_userequipment_image_alter_userequipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertree",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "กำลังดำเนินการ"),
                    ("completed", "ปลูกสำเร็จแล้ว"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
