# Generated by Django 5.1.6 on 2025-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_usertree_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertree",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usertree",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "กำลังดำเนินการ"),
                    ("completed", "ปลูกเสร็จแล้ว"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
