# Generated by Django 5.1.6 on 2025-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_usertree_updated_at_alter_usertree_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userequipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
